version: '3.5'

services:
  alert:
    image: grafana/grafana:4.6.3
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=3000
        - traefik.frontend.rule=Host:grafana.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
    volumes:
     - ./grafana/etc:/etc/grafana
     - ./grafana/data:/var/lib/grafana
     - /etc/timezone:/etc/timezone
     - /etc/localtime:/etc/localtime
    environment:
     - GF_SERVER_ROOT_URL=https://grafana.services.alin.be/
     - GF_SECURITY_ADMIN_PASSWORD=secret

networks:
  default:
    external:
      name: traefik-net
